"""add_ai_report_findings_and_metadata_fields

Revision ID: f6da9d51f044
Revises: 96187451c483
Create Date: 2026-08-30 22:49:55.192716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6da9d51f044'
down_revision: Union[str, None] = '96187451c483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    cols = [c['name'] for c in inspector.get_columns('ai_analysis_reports')]
    
    if 'patient_id' not in cols:
        op.add_column('ai_analysis_reports', sa.Column('patient_id', sa.Integer(), nullable=True))
    if 'total_findings' not in cols:
        op.add_column('ai_analysis_reports', sa.Column('total_findings', sa.Integer(), nullable=True, server_default='0'))
    if 'findings' not in cols:
        op.add_column('ai_analysis_reports', sa.Column('findings', sa.JSON(), nullable=True))
    if 'summary' not in cols:
        op.add_column('ai_analysis_reports', sa.Column('summary', sa.Text(), nullable=True))
    if 'disclaimer' not in cols:
        op.add_column('ai_analysis_reports', sa.Column('disclaimer', sa.Text(), nullable=True))
    if 'analysis_status' not in cols:
        op.add_column('ai_analysis_reports', sa.Column('analysis_status', sa.String(length=50), nullable=True, server_default='COMPLETED'))


def downgrade() -> None:
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescription_items_medication_name'), table_name='prescription_items')
    op.alter_column('prescription_items', 'drug_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_constraint(None, 'ai_analysis_reports', type_='foreignkey')
    op.drop_index(op.f('ix_ai_analysis_reports_patient_id'), table_name='ai_analysis_reports')
    op.drop_column('ai_analysis_reports', 'analysis_status')
    op.drop_column('ai_analysis_reports', 'disclaimer')
    op.drop_column('ai_analysis_reports', 'summary')
    op.drop_column('ai_analysis_reports', 'findings')
    op.drop_column('ai_analysis_reports', 'total_findings')
    op.drop_column('ai_analysis_reports', 'patient_id')
    # ### end Alembic commands ###
