"""create_appointment_management_tables

Revision ID: 16b58d05d2d2
Revises: 
Create Date: 2026-08-30 22:39:16.392369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b58d05d2d2'
down_revision: Union[str, None] = '000000000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    cols = [c['name'] for c in inspector.get_columns('appointments')]
    if 'reason' not in cols:
        op.add_column('appointments', sa.Column('reason', sa.Text(), nullable=True))
    if 'cancellation_reason' not in cols:
        op.add_column('appointments', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    if 'rejection_reason' not in cols:
        op.add_column('appointments', sa.Column('rejection_reason', sa.Text(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'rejection_reason')
    op.drop_column('appointments', 'cancellation_reason')
    op.drop_column('appointments', 'reason')
    # ### end Alembic commands ###
