"""add_patient_medical_history_and_lifestyle_fields

Revision ID: b76d1280f796
Revises: f6da9d51f044
Create Date: 2026-08-30 22:55:47.153411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b76d1280f796'
down_revision: Union[str, None] = 'f6da9d51f044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    cols = [c['name'] for c in inspector.get_columns('patient_profiles')]
    
    if 'past_conditions' not in cols:
        op.add_column('patient_profiles', sa.Column('past_conditions', sa.JSON(), nullable=True))
    if 'surgeries' not in cols:
        op.add_column('patient_profiles', sa.Column('surgeries', sa.JSON(), nullable=True))
    if 'current_medications' not in cols:
        op.add_column('patient_profiles', sa.Column('current_medications', sa.JSON(), nullable=True))
    if 'smoking_status' not in cols:
        op.add_column('patient_profiles', sa.Column('smoking_status', sa.String(length=30), nullable=True))
    if 'alcohol_consumption' not in cols:
        op.add_column('patient_profiles', sa.Column('alcohol_consumption', sa.String(length=30), nullable=True))
    if 'emergency_contact_name' not in cols:
        op.add_column('patient_profiles', sa.Column('emergency_contact_name', sa.String(length=100), nullable=True))
    if 'emergency_contact_phone' not in cols:
        op.add_column('patient_profiles', sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True))
    if 'emergency_contact_relationship' not in cols:
        op.add_column('patient_profiles', sa.Column('emergency_contact_relationship', sa.String(length=50), nullable=True))


def downgrade() -> None:
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescription_items_medication_name'), table_name='prescription_items')
    op.alter_column('prescription_items', 'drug_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('patient_profiles', 'chronic_conditions',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('patient_profiles', 'allergies',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('patient_profiles', 'emergency_contact_relationship')
    op.drop_column('patient_profiles', 'emergency_contact_phone')
    op.drop_column('patient_profiles', 'emergency_contact_name')
    op.drop_column('patient_profiles', 'alcohol_consumption')
    op.drop_column('patient_profiles', 'smoking_status')
    op.drop_column('patient_profiles', 'current_medications')
    op.drop_column('patient_profiles', 'surgeries')
    op.drop_column('patient_profiles', 'past_conditions')
    op.drop_constraint(None, 'ai_analysis_reports', type_='foreignkey')
    op.drop_index(op.f('ix_ai_analysis_reports_patient_id'), table_name='ai_analysis_reports')
    op.alter_column('ai_analysis_reports', 'analysis_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'COMPLETED'"))
    op.alter_column('ai_analysis_reports', 'total_findings',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###
