"""add_doctor_availability_and_unavailable_dates_tables

Revision ID: 7d9af077ad26
Revises: b76d1280f796
Create Date: 2026-08-30 23:01:32.623093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9af077ad26'
down_revision: Union[str, None] = 'b76d1280f796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'doctor_availabilities' not in tables:
        op.create_table('doctor_availabilities',
            sa.Column('doctor_id', sa.Integer(), nullable=False),
            sa.Column('day_of_week', sa.Integer(), nullable=False),
            sa.Column('start_time', sa.Time(), nullable=False),
            sa.Column('end_time', sa.Time(), nullable=False),
            sa.Column('slot_duration_minutes', sa.Integer(), nullable=False, server_default='30'),
            sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_doctor_availabilities_doctor_id'), 'doctor_availabilities', ['doctor_id'], unique=False)
        op.create_index(op.f('ix_doctor_availabilities_id'), 'doctor_availabilities', ['id'], unique=False)
        op.create_index('ix_doctor_availability_lookup', 'doctor_availabilities', ['doctor_id', 'day_of_week', 'is_active'], unique=False)

    if 'doctor_unavailable_dates' not in tables:
        op.create_table('doctor_unavailable_dates',
            sa.Column('doctor_id', sa.Integer(), nullable=False),
            sa.Column('unavailable_date', sa.Date(), nullable=False),
            sa.Column('reason', sa.String(length=255), nullable=True),
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_doctor_unavailable_date_lookup', 'doctor_unavailable_dates', ['doctor_id', 'unavailable_date'], unique=False)
        op.create_index(op.f('ix_doctor_unavailable_dates_doctor_id'), 'doctor_unavailable_dates', ['doctor_id'], unique=False)
        op.create_index(op.f('ix_doctor_unavailable_dates_id'), 'doctor_unavailable_dates', ['id'], unique=False)
        op.create_index(op.f('ix_doctor_unavailable_dates_unavailable_date'), 'doctor_unavailable_dates', ['unavailable_date'], unique=False)


def downgrade() -> None:
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescription_items_medication_name'), table_name='prescription_items')
    op.alter_column('prescription_items', 'drug_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('patient_profiles', 'chronic_conditions',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('patient_profiles', 'allergies',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'ai_analysis_reports', type_='foreignkey')
    op.drop_index(op.f('ix_ai_analysis_reports_patient_id'), table_name='ai_analysis_reports')
    op.alter_column('ai_analysis_reports', 'analysis_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'COMPLETED'"))
    op.alter_column('ai_analysis_reports', 'total_findings',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('ix_doctor_unavailable_dates_unavailable_date'), table_name='doctor_unavailable_dates')
    op.drop_index(op.f('ix_doctor_unavailable_dates_id'), table_name='doctor_unavailable_dates')
    op.drop_index(op.f('ix_doctor_unavailable_dates_doctor_id'), table_name='doctor_unavailable_dates')
    op.drop_index('ix_doctor_unavailable_date_lookup', table_name='doctor_unavailable_dates')
    op.drop_table('doctor_unavailable_dates')
    op.drop_index('ix_doctor_availability_lookup', table_name='doctor_availabilities')
    op.drop_index(op.f('ix_doctor_availabilities_id'), table_name='doctor_availabilities')
    op.drop_index(op.f('ix_doctor_availabilities_doctor_id'), table_name='doctor_availabilities')
    op.drop_table('doctor_availabilities')
    # ### end Alembic commands ###
